export interface PlayOptions {
  url: string
  streamType?: 'hls' | 'dash' | 'mp4'
  /** Keep this stream outside WARP (used by TDT Spain). */
  direct?: boolean
  licenseUrl?: string
  headers?: Record<string, string>
  drmHeaders?: Record<string, string>
  title?: string
  /** Explicit player mode: live TV, VOD, or YouTube resolved by NewPipe. */
  mode?: 'live' | 'vod' | 'youtube'
  startTime?: number
  /** Live TV: channel names for zapping overlay (up/down = prev/next channel) */
  channels?: string[]
  channelIndex?: number
  /** Current program info shown in the zap overlay */
  epgNow?: string
  epgNext?: string
  /** Current program start/end (epoch seconds) for the progress bar */
  epgStart?: number
  epgEnd?: number
  /** Channel logo URL — fallback when the channel list doesn't carry one */
  logo?: string
  /** IMDB id (tt…) para la búsqueda de subtítulos online (OpenSubtitles/Stremio) */
  imdbId?: string
  /** Temporada/episodio actuales (series) para la búsqueda de subtítulos */
  season?: number
  episode?: number
  /** Subtítulos side-loaded del proveedor (YouTube TTML/VTT, OpenSubtitles…) */
  subtitles?: Array<{ url: string; lang?: string; label?: string; mimeType?: string; autoGenerated?: boolean }>
  /** Series: episodios de la temporada actual para el panel lateral del player */
  episodes?: Array<{ name?: string; season?: number; episode?: number; watched?: boolean }>
  /** Índice del episodio en reproducción dentro de `episodes` */
  episodeIndex?: number
  /** Fuentes lentas (P2P/torrent): amplía el timeout de buffering a 90s y los reintentos */
  longBuffering?: boolean
  /** Texto de la pantalla de carga inicial (por defecto "Cargando enlace…") */
  loadingText?: string
}

export interface SetChannelsOptions {
  /** Live TV: channel list for the side panel / zap overlay */
  channels?: Array<{ name: string; now?: string; next?: string; start?: number; end?: number }>
  channelIndex?: number
}

export interface SwitchChannelOptions {
  url: string
  streamType?: 'hls' | 'dash' | 'mp4'
  /** Keep this channel outside WARP (used by TDT Spain). */
  direct?: boolean
  headers?: Record<string, string>
  title?: string
  channelIndex?: number
  epgNow?: string
  epgNext?: string
  epgStart?: number
  epgEnd?: number
}

export interface ChannelZapEvent {
  index: number
  direction: number
  name: string
}

export interface EpisodeSelectedEvent {
  index: number
  season: number
  episode: number
}

export interface SetEpisodesOptions {
  episodes?: Array<{ name?: string; season?: number; episode?: number; watched?: boolean }>
  episodeIndex?: number
}

export interface CastRequestedEvent {
  url?: string
  title?: string
}

export interface SeekOptions {
  position: number
}

export interface SetNextEpisodeOptions {
  title: string
  seriesName: string
  season: number
  episode: number
  poster?: string
  autoPlay?: boolean
}

export interface RateOptions {
  rate: number
}

export interface SetLoadingTextOptions {
  text: string
}

export interface PlaybackState {
  state: string
  message?: string
  errorCode?: number
}

export interface PlayEmbedOptions {
  url: string
  title?: string
  /** Referer para la petición inicial (players que lo exigen) */
  referer?: string
  /**
   * Modo reproducción: el vídeo se reproduce DENTRO del WebView (CDNs que
   * solo sirven al documento del proveedor, p.ej. los embeds DLive/tiestep).
   * No se extrae la URL ni se abre ExoPlayer; el diálogo queda abierto hasta
   * que el usuario cierra.
   */
  playback?: boolean
}

export interface PlayEmbedResult {
  status: string
  url?: string
  streamType?: string
  /** URL de la página final tras el challenge — usar como Referer */
  referer?: string
  /** Cookies capturadas del WebView para el dominio del stream */
  cookies?: string
}

export interface ResolveEmbedOptions {
  url: string
  /** Timeout en ms para el challenge/captcha (mínimo 5000) */
  timeout?: number
  /** Referer para la petición inicial (players que lo exigen) */
  referer?: string
}

export interface PlayRelayOptions {
  /** Media URL resuelta del embed (m3u8) */
  url: string
  /** Origen del documento del embed (p.ej. https://tiestep.top/) — el relay carga un doc stub en ese origen para que el CDN acepte las peticiones */
  referer?: string
  title?: string
  mode?: 'live' | 'vod'
}

export interface PlayRelayResult {
  status: string
}

export interface ExoPlayerPlugin {
  play(options: PlayOptions): Promise<{ status: string }>
  playEmbed(options: PlayEmbedOptions): Promise<PlayEmbedResult>
  /**
   * Resuelve un embed de forma invisible: WebView oculto que deja correr el
   * challenge JS (Cloudflare/captcha), hace auto-play e intercepta la URL del
   * vídeo. status: 'resolved' | 'failed' | 'busy'.
   */
  resolveEmbed(options: ResolveEmbedOptions): Promise<PlayEmbedResult>
  /**
   * Reproduce en ExoPlayer una media URL cuyo CDN solo la sirve al documento
   * del proveedor: relay local (WebView oculto en ese origen) que reenvía las
   * peticiones de playlist/segmentos. status: 'playing' | 'failed'.
   */
  playRelay(options: PlayRelayOptions): Promise<PlayRelayResult>
  switchChannel(options: SwitchChannelOptions): Promise<{ status: string }>
  setChannels(options: SetChannelsOptions): Promise<void>
  setEpisodes(options: SetEpisodesOptions): Promise<void>
  setNextEpisode(options: SetNextEpisodeOptions): Promise<void>
  /** Actualiza el texto del overlay de carga nativo (p.ej. progreso de torrent) */
  setLoadingText(options: SetLoadingTextOptions): Promise<void>
  pause(): Promise<void>
  resume(): Promise<void>
  stop(): Promise<void>
  /** Busca pantallas Miracast/WiFi Direct y conecta o abre los ajustes del sistema */
  openMiracast(): Promise<{ connected: boolean; device?: string; peers?: string[] }>
  /** Escanea la red buscando TVs DLNA y envía la URL a la primera encontrada */
  openDlna(options: { url: string; title?: string }): Promise<{ sent: boolean; device?: string; reason?: string }>
  seekTo(options: SeekOptions): Promise<void>
  setPlaybackRate(options: RateOptions): Promise<void>
  addListener(eventName: 'playbackState', listener: (state: PlaybackState) => void): Promise<{
    remove: () => void
  }> | { remove: () => void }
  addListener(eventName: 'channelZap', listener: (event: ChannelZapEvent) => void): Promise<{
    remove: () => void
  }> | { remove: () => void }
  addListener(eventName: 'episodeSelected', listener: (event: EpisodeSelectedEvent) => void): Promise<{
    remove: () => void
  }> | { remove: () => void }
  addListener(eventName: 'castRequested', listener: (event: CastRequestedEvent) => void): Promise<{
    remove: () => void
  }> | { remove: () => void }
}
