export interface ResolveOptions {
  url: string
}

export interface VideoStream {
  url: string
  mimeType: string
  quality: string
  format: 'mp4' | 'webm' | 'm3u8'
}

export interface SubtitleTrack {
  url: string
  language: string
  name: string
  autoGenerated: boolean
  mimeType: string
}

export interface ResolveResult {
  title: string
  streams: VideoStream[]
  dashUrl?: string
  hlsUrl?: string
  subtitles?: SubtitleTrack[]
}

export interface SearchOptions {
  query: string
}

export interface SearchResultItem {
  name: string
  url: string
  uploader: string
  duration: number
  views: number
  thumbnailUrl: string
  isLive: boolean
}

export interface SearchPageData {
  url?: string
  id?: string
  ids?: string[]
  cookies?: Record<string, string>
  body?: string
}

export interface SearchResult {
  items: SearchResultItem[]
  hasNextPage?: boolean
  nextPage?: SearchPageData
}

export interface SearchMoreOptions {
  query: string
  nextPage: SearchPageData
}

export interface SuggestOptions {
  query: string
}

export interface SuggestResult {
  suggestions: string[]
}

export interface GetChannelOptions {
  channelId?: string
  url?: string
}

export interface ChannelInfo {
  name: string
  url: string
  description: string
  subscriberCount: number
  avatarUrl: string
  bannerUrl: string
  items: SearchResultItem[]
}

export interface ChannelInfoLite {
  name: string
  url: string
  subscriberCount: number
  avatarUrl: string
}

export interface YoutubePlugin {
  resolve(options: ResolveOptions): Promise<ResolveResult>
  search(options: SearchOptions): Promise<SearchResult>
  searchMore(options: SearchMoreOptions): Promise<SearchResult>
  suggest(options: SuggestOptions): Promise<SuggestResult>
  getChannel(options: GetChannelOptions): Promise<ChannelInfo>
  getChannelInfo(options: GetChannelOptions): Promise<ChannelInfoLite>
}
