import { isAndroidNative } from './platform.js'

let youtubePlugin = null

async function getPlugin() {
  if (!isAndroidNative()) return null
  if (!youtubePlugin) {
    try {
      const mod = await import('@octostream/youtube')
      // Wrap in a plain object to prevent JS from calling .then() on the
      // Capacitor proxy (which would trigger "not implemented on android")
      youtubePlugin = { impl: mod.Youtube }
    } catch (e) {
      console.warn('[YouTube] Plugin not available:', e?.message)
      return null
    }
  }
  return youtubePlugin
}

/**
 * Resolve a YouTube URL (watch, embed, or youtu.be) into direct video streams.
 * Uses NewPipeExtractor on Android to get direct MP4/WebM URLs.
 * @param {string} url - YouTube URL (watch?v=, /embed/, youtu.be/)
 * @returns {Promise<{title: string, streams: Array<{url, mimeType, quality, format}>} | null>}
 */
export async function resolveYouTube(url) {
  const wrapper = await getPlugin()
  if (!wrapper) return null

  // Normalize URL: convert /embed/ to /watch?v= (NewPipeExtractor handles both, but watch is safer)
  let normalizedUrl = url
  const embedMatch = url.match(/youtube\.com\/embed\/([a-zA-Z0-9_-]+)/)
  if (embedMatch) {
    normalizedUrl = `https://www.youtube.com/watch?v=${embedMatch[1]}`
  } else if (url.includes('youtu.be/')) {
    const shortMatch = url.match(/youtu\.be\/([a-zA-Z0-9_-]+)/)
    if (shortMatch) {
      normalizedUrl = `https://www.youtube.com/watch?v=${shortMatch[1]}`
    }
  }

  try {
    console.log('[YouTube] Resolving:', normalizedUrl)
    const result = await wrapper.impl.resolve({ url: normalizedUrl })
    console.log(`[YouTube] Resolved: ${result.title} → ${result.streams?.length || 0} streams`)
    return result
  } catch (e) {
    console.warn('[YouTube] Failed to resolve:', e?.message)
    return null
  }
}

// Caché de streams resueltos: las URLs firmadas de googlevideo duran ~6h.
// TTL 15 min da margen de sobra y hace casi instantánea la reanudación desde
// "Continuar viendo" o volver a pulsar el mismo vídeo. Si una URL caducara el
// player la re-resuelve sola vía stream._refreshUrl.
const streamCache = new Map() // videoId → { ts, stream }
const inflight = new Map()    // videoId → Promise (dedup prefetch vs click)
const STREAM_CACHE_TTL_MS = 15 * 60 * 1000

function ytVideoId(url) {
  const m = String(url || '').match(/(?:watch\?v=|embed\/|youtu\.be\/|shorts\/)([a-zA-Z0-9_-]{6,})/)
  return m ? m[1] : null
}

export function invalidateYouTubeStream(url) {
  const id = ytVideoId(url)
  if (id) streamCache.delete(id)
}

/**
 * Resuelve en background para llenar la caché (prefetch al enfocar una
 * tarjeta). Nunca lanza — los fallos se ignoran: el click resolverá de nuevo.
 */
export function prefetchYouTubeStream(url) {
  const id = ytVideoId(url)
  if (!id) return
  const hit = streamCache.get(id)
  if (hit && Date.now() - hit.ts < STREAM_CACHE_TTL_MS) return
  resolveYouTubeStream(url).catch(() => {})
}

/**
 * Get the best playable stream from YouTube resolution.
 * Prefers progressive (muxed audio+video) MP4 streams.
 * @returns {Promise<{url: string, streamType: string, quality: string, title: string} | null>}
 */
export async function resolveYouTubeStream(url, { force = false } = {}) {
  const id = ytVideoId(url)
  if (!force && id) {
    const hit = streamCache.get(id)
    if (hit && Date.now() - hit.ts < STREAM_CACHE_TTL_MS) {
      console.log('[YouTube] Stream cache hit:', id)
      return { ...hit.stream }
    }
    const pending = inflight.get(id)
    if (pending) return pending
  }

  const work = (async () => {
    const result = await resolveYouTube(url)
    if (!result) return null

  const subtitles = (result.subtitles || [])
    .filter(s => s && s.url)
    .map(s => ({
      url: s.url,
      lang: s.language || '',
      label: s.name || (s.language || '').toUpperCase() || 'Subtítulos',
      autoGenerated: s.autoGenerated === true,
      mimeType: s.mimeType || 'application/ttml+xml',
    }))

    // Directos → HLS. VOD → manifest DASH (adaptativo: todas las calidades y
    // pistas de audio → selector de calidad real en ExoPlayer). Fallback al
    // mejor MP4 progresivo si el vídeo no expone manifest.
    // direct: true → YouTube NUNCA va por el proxy WARP: googlevideo y el
    // endpoint timedtext de subtítulos devuelven 429 desde IPs de datacenter
    // (Cloudflare WARP). YouTube no está bloqueado por ISP, no lo necesita.
    const direct = true
    if (result.hlsUrl) {
      return { url: result.hlsUrl, streamType: 'hls', quality: 'Live', title: result.title, subtitles, direct }
    }
    if (result.dashUrl) {
      return { url: result.dashUrl, streamType: 'dash', quality: '', title: result.title, subtitles, direct }
    }
    if (!result.streams || result.streams.length === 0) return null

    // Prefer mp4 progressive streams (muxed audio+video)
    const mp4Streams = result.streams.filter(s => s.mimeType?.includes('mp4'))
    const bestStream = (mp4Streams.length > 0 ? mp4Streams : result.streams)[0]

    return {
      url: bestStream.url,
      streamType: 'mp4',
      quality: bestStream.quality || '',
      title: result.title,
      subtitles,
      direct,
    }
  })()

  if (!id) return work
  inflight.set(id, work)
  try {
    const stream = await work
    if (stream) streamCache.set(id, { ts: Date.now(), stream })
    return stream
  } finally {
    if (inflight.get(id) === work) inflight.delete(id)
  }
}

/**
 * Search YouTube videos using NewPipeExtractor, with pagination support.
 * @param {string} query - Search query
 * @param {object|null} nextPage - Continuation page from a previous search
 * @returns {Promise<{items: Array, nextPage: object|null} | null>}
 */
export async function searchYouTubeFull(query, nextPage = null) {
  const wrapper = await getPlugin()
  if (!wrapper) return null

  try {
    const result = nextPage
      ? await wrapper.impl.searchMore({ query, nextPage })
      : await wrapper.impl.search({ query })
    console.log(`[YouTube] Search returned ${result.items?.length || 0} results, hasNext=${!!result.nextPage}`)
    return { items: result.items || [], nextPage: result.nextPage || null }
  } catch (e) {
    console.warn('[YouTube] Search failed:', e?.message)
    return null
  }
}

/**
 * Search YouTube videos using NewPipeExtractor.
 * @param {string} query - Search query
 * @returns {Promise<Array<{name, url, uploader, duration, views, thumbnailUrl, isLive}> | null>}
 */
export async function searchYouTube(query) {
  const result = await searchYouTubeFull(query)
  return result ? result.items : null
}

/**
 * Get search suggestions from YouTube using NewPipeExtractor.
 * @param {string} query - Partial search query
 * @returns {Promise<string[] | null>}
 */
export async function suggestYouTube(query) {
  const wrapper = await getPlugin()
  if (!wrapper) return null

  try {
    const result = await wrapper.impl.suggest({ query })
    return result.suggestions || []
  } catch (e) {
    console.warn('[YouTube] Suggest failed:', e?.message)
    return null
  }
}


